apiVersion: v1
kind: Secret
metadata:
  name: mcp-kubeconfigs
  namespace: mcp-k8s
type: Opaque
data:
  cluster1.kubeconfig: <Put your kubeconfig base64 here>
  cluster2.kubeconfig: <Put your kubeconfig base64 here>